FROM python:alpine

WORKDIR /app

# Install system packages if needed
RUN apt-get update && apt-get install -y build-essential

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the code and metadata file
COPY . .

# Optional: if .env exists locally, you can COPY it or use docker run --env-file
CMD ["python", "upload_metadata.py"]
